#!/bin/tcsh
# $Revision: 6 $, $Date: 2009-03-10 20:13:07 +0000 (Tue, 10 Mar 2009) $
# $URL: http://i3rc-monte-carlo-model.googlecode.com/svn/trunk/Clean $

echo "Cleaning in Code directory"; cd Code; make clean; cd ..
echo "Cleaning in Integrators directory"; cd Integrators; make clean; cd ..
echo "Cleaning in Example-Drivers directory"; cd Example-Drivers; make clean; cd ..
echo "Cleaning in Tools directory"; cd Tools; make clean; cd ..
